/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import 'radial-rep';


export namespace Components {

  interface TableCrispr {
    'complete_data': string;
  }
  interface TableCrisprAttributes extends StencilHTMLAttributes {
    'complete_data'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'TableCrispr': Components.TableCrispr;
  }

  interface StencilIntrinsicElements {
    'table-crispr': Components.TableCrisprAttributes;
  }


  interface HTMLTableCrisprElement extends Components.TableCrispr, HTMLStencilElement {}
  var HTMLTableCrisprElement: {
    prototype: HTMLTableCrisprElement;
    new (): HTMLTableCrisprElement;
  };

  interface HTMLElementTagNameMap {
    'table-crispr': HTMLTableCrisprElement
  }

  interface ElementTagNameMap {
    'table-crispr': HTMLTableCrisprElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
